<a href="https://colab.research.google.com/github/jasman5/UCS547-Accelerated-Data-Science/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lab Assignment -1
(UCC547)

1. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )

In [1]:
import numpy as np


In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])

reversed_arr = arr[::-1]
print("Original Array:", arr)
print("Reversed Array:", reversed_arr)


Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]


2. Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

comparison = np.array_equal(arr1, arr2)
print("Are both arrays equal?", comparison)


Are both arrays equal? True


3. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )
Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
     ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [4]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)

print("Most Frequent Value:", most_frequent)
print("Indices:", indices[0])


Most Frequent Value: 1
Indices: [0 5 7 8 9]


In [5]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)

print("Most Frequent Value:", most_frequent)
print("Indices:", indices[0])


Most Frequent Value: 1
Indices: [0 1 2]


4. For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),find
i. Sum of all elements
ii.Sum of all element’s row-wise
iii. Sum of all element’s column-wise

In [6]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Matrix:\n", gfg)


Matrix:
 [[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]


In [7]:
total_sum = np.sum(gfg)
print("Sum of all elements:", total_sum)


Sum of all elements: 45


In [8]:
row_sum = np.sum(gfg, axis=1)
print("Row-wise sum:\n", row_sum)


Row-wise sum:
 [[14]
 [16]
 [15]]


In [9]:
col_sum = np.sum(gfg, axis=0)
print("Column-wise sum:\n", col_sum)


Column-wise sum:
 [[20  9 16]]
